### ISSUE TITLE
Setup Kanban board project

### ISSUE THREAD

**Issue by stephnna** [Ibizugbe/catalog_of_my_things#35]
Hi code reviewer,
My partners and I implemented the kanban board projects

Here is the project link https://github.com/users/Ibizugbe/projects/1
We are three 
@XsidX is working on team #1
@Ibizugbe is working on #2
and @stephnna  is working on #3

Kindly review as required.
Thank you!

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Ibizugbe, @stephnna, and @XsidX👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Most of the task cards don't have descriptions, Please make sure to add descriptions to all of your task cards.
![image](https://user-images.githubusercontent.com/83803414/194845919-9af81d9a-77a9-4884-9a1b-2e969e3f0049.png)

- [ ] Time estimate distributions should be fair (no single person should be doing all of the most time-consuming tasks). The points are not divided equally among team members. Please make sure the point distributions are fair and equal.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ibizugbe** [comment]
Thanks @thecodechaser for reviewing our project, we will do well to implement the required changes immediately.

**Comment by Wes-Isaac** [comment]
Hi  @Ibizugbe, @stephnna, and @XsidX,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Kanban board setup correctly 🚀.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ibizugbe** [comment]
Thanks, @Wes-Isaac for reviewing and approving the PR
